import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import { SessionProvider } from "next-auth/react";
import { WishlistProvider } from "@/context/WishlistContext";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WishlistProvider>
      
          
          <Navbar />

          <div className="container mx-auto p-3">
            <Toaster />
            {children}
          </div>

          <Footer />
  
        </WishlistProvider>
      </body>
    </html>
  );
}
